### ISSUE TITLE
Allow to define zowe.yaml in PARMLIB

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#2488]
Currently v1 instance.env and v2 zowe.yaml must exist on USS side, and the user must define/modify the file with USS related commands, typically using SSH with vi command.

Would like to allow the user to define the zowe.yaml in their PARMLIB, for example `IBMUSER.ZWE.PARMLIB(ZOWEYAML)` and this allows the user to:

- start Zowe by pointing to this parmlib member: `S ZWESLSTC,CONFIG=IBMUSER.ZWE.PARMLIB(ZOWEYAML),JOBNAME=ZWE1SV` instead of starting Zowe with USS command `zwe start --config /path/to/my/zowe.yaml`.
- provide `ZOWEYAML` in `SZWESAMP` to list the most commonly used customization entries, like external domain name, zOSMF host/port, node path, etc.
- configure Zowe by modifying this ZOWEYAML that:
  * each configuration entry can be represented as `flat` yaml format. For example, in normal case, we ask the user to define `zowe.yaml` like:
    ```yaml
    zowe:
      logDirectory: /path/to/my/log
    components:
      gateway:
        port: 12345
    zOSMF:
        # comment on my zosmf config
        port: 10443
    ```
    With `flat` definition, the above configuration are identical to:
    ```yaml
    zowe.logDirectory: /path/to/my/log
    components.gateway.port: 12345
    # comment on my zosmf config
    zOSMF.port: 10443
    ```
