### ISSUE TITLE
v2  "zwe init" cannot setup datasets

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zowe-install-packaging#2542]
When I run "zwe init" I run into this issue.
When I inspect the datasets referenced, they all exist, but the ones where the copy was supposed to occur instead have corrupted members.
If I manually copy the members from one dataset to another, it works perfectly fine. So, something is wrong with this automation.

```
-------------------------------------------------------------------------------
>> Install Zowe main started task

Modify ZWESLSTC
Modify ZWESISTC
Modify ZWESASTC

Copy ME.ZWE2008.CUST.JCLLIB(ZWESLSTC) to ME.ZWE2008.PRCLIB(ZWESLSTC)
  * Exit code: 12
  * Output:
    exec 'ME.ZWE2008.SZWEEXEC(MCOPYSHR)' 'ME.ZWE2008.CUST.JCLLIB(ZWESLSTC) ME.ZWE2008.PRCLIB(ZWESLSTC)'
    IKJ56247I FILE ZWESIN NOT FREED, IS NOT ALLOCATED
    IKJ56247I FILE ZWESOUT NOT FREED, IS NOT ALLOCATED
    IKJ56228I DATA SET ME.ZWE2008.PRCLIB NOT IN CATALOG OR CATALOG CAN NOT BE ACCESSED
    IKJ56701I MISSING DATA SET NAME+
    IKJ56701I MISSING NAME OF DATA SET TO BE ALLOCATED
Error ZWEL0111E: Command aborts with error.
```

**Comment by jackjia-ibm** [comment]
Seems `ME.ZWE2008.PRCLIB` is not created, which should be in `zwe init mvs` step.

What's the setup of:

```
zowe:
  setup:
    mvs:
      hlq: IBMUSER.ZWEV2
      parmlib: IBMUSER.ZWEV2.CUST.PARMLIB
      jcllib: IBMUSER.ZWEV2.CUST.JCLLIB
```

Do you see any failures in `zwe init mvs` step? More info could show if you pass `-vv` like `zwe init -vv` (trace mode).

**Comment by struga0258** [comment]
Is zwe init supposed to create the proclib? because i was running into this issue as well and now im creating the proclib manually before running this, here is my setup:

```
mvs:
      # where Zowe MVS data sets will be installed
      hlq: TS3215.ZWE0
      # PROCLIB where Zowe STCs will be copied over
      proclib: TS3215.USER.PROCLIB
      # Zowe PARMLIB
      parmlib: TS3215.ZWEV0.CUST.PARMLIB
      # JCL library where Zowe will store temporary JCLs during initialization
      jcllib: TS3215.ZWEV0.CUST.JCLLIB
      # APF authorized LOADLIB for Zowe
      # Optional. If it's empty, <hlq>.SZWEAUTH will be APF authorized.
      authLoadlib:
      # APF authorized LOADLIB for Zowe ZIS Plugins
      authPluginLib: TS3215.ZWEV0.CUST.ZWESAPL
```
