### ISSUE TITLE
v2 certificates bug

### ISSUE THREAD

**Issue by struga0258** [zowe/zowe-install-packaging#2544]
In the example-zowe.yaml we see the following under certificate:
```
certificate:
    pem:
      key: /global/zowe/keystore/localhost/localhost.keystore.key
      certificate: /global/zowe/keystore/localhost/localhost.keystore.cer-ebcdic
      certificateAuthority: /global/zowe/keystore/local_ca/localca.cer-ebcdic
```

But after running generating the certificate i noticed that inside of the localhost folder `localhost.keystore.key` and `localhost.keystore.cer-ebcdic` and we manually need to replace them to be `localhost.key` and `localhost.cer-ebcdic`
