### ISSUE TITLE
Certificate section confusion

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zowe-install-packaging#2565]
The current zowe yaml config section shows

```

  # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # Default Zowe certificate
  #
  # **NOTE**: these fields can be updated automatically if you pass
  # `--update-config` to `zwe init` command. The generated value will base on
  # your setup in `zowe.setup.certificate` section.
  certificate:
    keystore:
      type: PKCS12
      file: /global/zowe/keystore/localhost/localhost.keystore.p12
      password: password
      alias: localhost
    truststore:
      type: PKCS12
      file: /global/zowe/keystore/localhost/localhost.truststore.p12
      password: password
    pem:
      key: /global/zowe/keystore/localhost/localhost.key
      certificate: /global/zowe/keystore/localhost/localhost.cer
      certificateAuthorities: /global/zowe/keystore/local_ca/local_ca.cer
```

If I changed my keystore location, then these paths are wrong, but probably updated when I do `--update-config`
But, can these default instead to relative paths?
Can we do
      `file: ${ZWE_zowe_setup_certificate_pkcs12_directory}/localhost/localhost.keystore.p12`
or
      `file: ./localhost/localhost.keystore.p12`
