### ISSUE TITLE
Component dependency tracking in manifest

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zowe-install-packaging#3167]
Some components have dependencies on others, or even content outside of Zowe.
You could say for example,

Dependencies

jobs:
* java must exist (and within the version range of zowe's support)
* gateway & discovery must be running
* zosmf must be attached to the gateway

jes-explorer:
* gateway, discovery, and app-server must be running
* zosmf must be attached to the gateway

app-server:
* node must exist (and within the version range of zowe's support)

zss:
* must be running on z/os

i'm sure we can learn some lessons from npm package.json, but in general i see a possible structure for capturing all of this info by putting it into manifest.yaml like so,

jobs:
```
dependencies:
  core:
    environment:
      java:
        versionRange: zowe
    components:
      gateway:
        provider: zosmf
      discovery:
        registeredComponents:
          - zosmf
```

app-server:
```
dependencies:
    core:
      environment:
        node:
          versionRange: zowe
```

zss:
```
dependencies:
  core:
    environment:
      platform: 
        type: zos
        versionRange: >=2.4
```

i'm trying to think of a structure that is futureproof and allows us to say things simply.
i dont think zowe core will be able to check every value that could possibly be contained here, but rather this area may be used by extensions too to perform further dependency validation. Zowe could just ship with some `core` validation features, and if the `dependencies` section had attributes other than `core`, it might signal the name of an extension that should be invoked according to some API to perform further dependency validation.
