### ISSUE TITLE
ZOWE New install RACF KEYSTORE ZWED0149E

### ISSUE THREAD

**Issue by dep81** [zowe/zowe-install-packaging#3413]
Hello, 

I am working/struggling with a  new install of ZOWE and am using RACF keystore certificates.   Security person used the sample KEYRING job, but I keep getting the following errors

ZWED0149E - SAF keyring reference missing userId "", keyringName "ZWESVUSR/ZoweKeyring", or label "ZWESVUSR/ZoweKeyring&Zowe localCA" 
ZWED0149E - SAF keyring reference missing userId "", keyringName "ZWESVUSR/ZoweKeyring", or label "ZWESVUSR/ZoweKeyring&Zowe localCA" 
ZWED0149E - SAF keyring reference missing userId "", keyringName "ZWESVUSR/Keyring", or label "Zowe localCA"                          

from the yaml 
certificate:                                                              
  keystore:                                                               
    type: JCERACFKS                                                       
    file: safkeyring:///ZWESVUSR/ZoweKeyring                              
    password: 'password'                                                  
    alias: "ZWESVUSR/ZoweKeyring&Zowe localCA"                            
  truststore:                                                             
    type: JCERACFKS                                                       
    file: safkeyring:///ZWESVUSR/ZoweKeyring                              
    password: 'password'                                                  
  pem:                                                                    
    key: ""                                                               
    certificate: ""                                                       
    certificateAuthorities: "safkeyring:///ZWESVUSR/Keyring&Zowe localCA" 
                                                                          
I have tried every variations but same outcome and not able to logon to explorer - nothing show listening on port 7554. 

Figure it is something stupid, but I cant's see the forest for the trees.

Appreciate any insight.

**Comment by 1000TurquoisePogs** [comment]
Yes, this is an invalid keyring configuration. You need to read https://docs.zowe.org/stable/user-guide/configure-certificates-keyring to ensure your keyring is valid before making your configuration valid as well.
You have:

```
certificate:
  keystore:
    type: JCERACFKS
    file: safkeyring:///ZWESVUSR/ZoweKeyring
    password: 'password'
    alias: "ZWESVUSR/ZoweKeyring&Zowe localCA"
  truststore:
    type: JCERACFKS
    file: safkeyring:///ZWESVUSR/ZoweKeyring
    password: 'password'
  pem:
    key: ""
    certificate: ""
    certificateAuthorities: "safkeyring:///ZWESVUSR/Keyring&Zowe localCA"
```

The document suggests a similar structure but your keystore alias value is wrong. It's more like "alias: localhost". it's whatever the name of the key or cert is in the keyring. It's not a CA, so it wont be "Zowe localCA" either.

Moving this ticket to an appropriate queue.
