### ISSUE TITLE
Zwe commands unable to process long string in zowe.yaml

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/zowe-install-packaging#3476]
**Describe the bug**
When a long string is used in `zowe.yaml` file, commands are not processed correctly.

**To Reproduce**
1. Create `zowe.yaml` file like this with a string more than 432 characters (valid unix path is 1023):
```
zowe:
  setup:
    dataset:
      prefix: USERID.ZOWE
      parmlib: USERID.ZOWE.PARMLIB
      jcllib: USERID.ZOWE.JCLLIB
      authLoadlib:  USERID.ZOWE.TEST1
      authPluginLib:  USERID.ZOWE.TEST2
  useConfigmgr: true
  runtimeDirectory: /u/userid/myyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy/zoweeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/versionnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn/2.9.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```
2. Run `zwe` command: `zwe config get -c zowe.yaml -p zowe`
3. Output is missing the requested result:
```
Temporary directory '/tmp/.zweenv-2816' created.
Zowe will remove it on success, but if zwe exits with a non-zero code manual cleanup would be needed.
```

**Expected behavior**
Output with the verified structure:
```
Temporary directory '/tmp/.zweenv-3028' created.
Zowe will remove it on success, but if zwe exits with a non-zero code manual cleanup would be needed.
{"setup":{"dataset":{"prefix":"USERID.ZOWE","parmlib":"USERID.ZOWE.PARMLIB","jcllib":"USERID.ZOWE.JCLLIB","authLoadlib":"USERID.ZOWE.TEST1","authPluginLib":"USERID.ZOWE.TEST2"}},"useConfigmgr":true,"runtimeDirectory":"/u/userid/myyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy/zoweeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/versionnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn/2.9.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"}
Temporary directory /tmp/.zweenv-3028 removed successfully.
```

**Technical details**
- zowe 2.8.0, 2.9.0 and 2.10.0 (find while working on other PR, which is 2.10.0)
- OS: OS/390 LPAR 28.00 04 8561
- Node: v14.21.3 and v18.12.1

**Additional context**
Good news, I have a solution.
Bad news, I have no idea, why it works...
While debugging, it was obvious, that [writeYAML](https://github.com/zowe/zowe-install-packaging/blob/75a8a2781092d1cb30f2f4bd5265740588778351/bin/libs/configmgr.ts#L308) is not called for the "incorrect" `zowe.yaml`. 
I was comparing the values, which are used and created for the "correct" and "incorrect" `zowe.yaml` file, included the debug messages in `writeYAMLWrapper`. 
After zillion debug messages I made unintentionally typo and it started to work...
A tiny change in [getConfigRevisionName](https://github.com/zowe/zowe-install-packaging/blob/75a8a2781092d1cb30f2f4bd5265740588778351/bin/libs/configmgr.ts#L338) (this is JS version):
```
function getConfigRevisionName(configName, revision) {
    (revision === undefined) ? revision = CONFIG_REVISIONS[configName] : revision = 0;
    return configName + '_rev' + revision;
}
```
I would love to know, what the heck is going on here... 😄
