### ISSUE TITLE
bin/libs/zos-dataset.ts: tsoCommand and dollar sign in dataset name

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/zowe-install-packaging#3648]
`zowe.yaml` is:
```
zowe:                          
  setup:                       
    dataset:                   
      prefix: ZOWE.X$-$
```

Run `zwe install -c zowe.yaml`.
Following datasets are created:
```
ZOWE.XH$.SZWEAUTH
ZOWE.XH$.SZWEEXEC
ZOWE.XH$.SZWELOAD
ZOWE.XH$.SZWESAMP
```
**Reason**
At some point we call [`tsocmd "ALLOCATE NEW DA('ZOWE.X$-$')"`](https://github.com/zowe/zowe-install-packaging/blob/b31828d2ff9813c77efdd11b9ac394d4cef21d44/bin/libs/zos-dataset.ts#L47). This is treated as any other `shell` command, `$-` is substituted with value, which is in this case some shell flag.

**Expectation**
We should be able to decide if shell variable or dollar sign is used.
In this example we should call `tsocmd "ALLOCATE NEW DA('ZOWE.X\$-\$')"`
