### ISSUE TITLE
Certificate issue after update to version 2.16

### ISSUE THREAD

**Issue by rudatp** [zowe/zowe-install-packaging#3872]
We are using SAF keyrings, yaml section:

certificate:
  keystore:
    type: JCERACFKS
    file: "safkeyring:////STCZOWE/ZOWE"
    password: "password"
    alias: "ZOWE25"
  truststore:
    type: JCERACFKS
    file: "safkeyring:////STCZOWE/ZOWE"
    password: "password"
  pem:
    key:
    certificate:
    certificateAuthorities:
    - "safkeyring:////STCZOWE/CA1"
    - "safkeyring:////STCZOWE/CA2"

I updated ZOWE today to version 2.16 and startup fails with:

Validity Exceptions(s) with object at
  Validity Exceptions(s) with object at /zowe
    Schema at '/zowe/certificate' invalid
      not oneOf schemas at '/zowe/certificate' are valid, 0 are
        Validity Exceptions(s) with object at /zowe/certificate
          Validity Exceptions(s) with object at /zowe/certificate/keystore
            unequal constant value at /zowe/certificate/keystore/type; expecting value 'PKCS12' of type 'string'
          Validity Exceptions(s) with object at /zowe/certificate/truststore
            unequal constant value at /zowe/certificate/truststore/type; expecting value 'PKCS12' of type 'string'
          Validity Exceptions(s) with object at /zowe/certificate/pem
            type 'null' not permitted at /zowe/certificate/pem/key; expecting type 'string'
            type 'null' not permitted at /zowe/certificate/pem/certificate; expecting type 'string'
        Validity Exceptions(s) with object at /zowe/certificate
          Validity Exceptions(s) with object at /zowe/certificate/pem
            type 'null' not permitted at /zowe/certificate/pem/key; expecting type 'string'
            type 'null' not permitted at /zowe/certificate/pem/certificate; expecting type 'string'

Can someone help?

**Comment by Martin-Zeithaml** [comment]
Hi,
the problem is, there is no value provided for `/zowe/certificate/pem/key` and `zowe/certificate/pem/certificate`. The schema validation is strict and requires a value. To avoid the schema validation problem, remove unused fields:
```
certificate:
  keystore:
    type: JCERACFKS
    file: "safkeyring:////STCZOWE/ZOWE"
    password: "password"
    alias: "ZOWE25"
  truststore:
    type: JCERACFKS
    file: "safkeyring:////STCZOWE/ZOWE"
    password: "password"
  pem:
    certificateAuthorities:
    - "safkeyring:////STCZOWE/CA1"
    - "safkeyring:////STCZOWE/CA2"
```
