### ISSUE TITLE
zwe init mvs fails with complaint about zowe.yaml

### ISSUE THREAD

**Issue by gejohnston** [zowe/zowe-install-packaging#4090]
**Describe the bug**
A PSWI-generated workflow job does not like the zowe.yaml file that was also generated by the PSWI workflow.

**To Reproduce**

Run the step "PSWI - Deployment - Workflows - Configuration of Zowe 3.0 - Run the Zowe init"

The job fails with CC=3328 and displays the following error message:

```
zwe init mvs -c /u/users/group/product/zwe/zowe-smpe/zowe.yaml --allow-overwrite
* Output:
node: read_yaml 10: /u/users/group/product/zwe/zowe-smpe/bin/commands/init/mvs/index.sh 28: .: zwecli_process_command 4: /u/users/group/product/zwe/zowe-smpe/bin/zwe 98: FSUM7351 not found
Error ZWEL0157E: Zowe dataset prefix (zowe.setup.dataset.prefix) is not defined in Zowe YAML configuration file.
```

The zowe.yaml file is generated by the PSWI workflow. Identifying an error in the yaml file does not relate to any action that the user performed.

By debugging the yaml file anyway, I find a path that looks exactly like what the error says is not defined.

```yaml
#-------------------------------------------------------------------------------
zowe:
  #-------------------------------------------------------------------------------
  # These configurations are used by "zwe install" or "zwe init" commands.
  #-------------------------------------------------------------------------------
  setup:
    # MVS data set related configurations
    dataset:
      # **COMMONLY_CUSTOMIZED**
      # where Zowe MVS data sets will be installed
      prefix: IBMUSER.ZWEV2

```

Having to further speculate on what the error might be actually complaining about, I find that the dataset does not exist. Is that what the error is actually about?

```
-> zowe zos-files list data-set "IBMUSER"
IBMUSER.ISPF.ISPPROF
IBMUSER.RECEIVE.MAIL
```

I do not recall any doc instructing me to create such a dataset. I manually created a dataset by that name just to confirm that I am privileged to do so.

```
-> zowe zos-files list data-set "IBMUSER"
IBMUSER.ISPF.ISPPROF
IBMUSER.RECEIVE.MAIL
IBMUSER.ZWEV2
```

**Expected behavior**

Since the yaml file and the jobs are all generated behind the scenes, either the PSWI workflow has an error, or the doc does not have sufficient instructions for the user to set PSWI properties that will succeed when the workflow job is run.

The value 'IBMUSER.ZWEV2' is the default value in the step "PSWI - Deployment - Workflows - Configuration of Zowe 3.0 - Define the main variables - Zowe setup MVS prefix". I simply accepted the default value.

By the way, if that is a value which we recommend to customers, it should probably be named 'V3'.

**Desktop (please complete the following information):**
 - OS: Windows 11, z/OS 3.1
 - Browser: Chrome
 - Version: 131.0.6778.70
