### ISSUE TITLE
Create Metrics Server w/ SDSF and RMF

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#619]
**Summary**

The metric server:
- is a service running on z/OS,
- is configurable and can interpret a configuration file in pre-defined format,
- can start dependent services (like RMF or CIM server) if required during startup,
- is able to poll server metrics based on the configuration setup and store the metrics in memory,
- provides HTTP and also WebSocket service to expose metrics data to other consumers,
- web service and collectors should be started on different threads (do we need to implement workers?).

**Questions:**

- Measure the impact of collectors

**Programming Language**

Ideally should be written in more efficient language like C, golang, but we may use node.js if we can handle threads properly.

- Node.JS
- TBD

**Configurations**

The configuration file is in YAML format for human reading and commenting.

Example configuration file:
```yaml
default-collector: RMF
rmf:
    # configs for rmf server
cim:
   # configs for cim server
defaults:
  interval: 5s  # if on-demand is false, this interval won't take effect
  on-demand: true/false
metrics:
- cpu: 
  smf: 70
- cpu.[process]:
- cpu-time:
- cpu-time.[process]:
- memory:
- memory.[process]:
- page-swap:
- page-swap.[process]:
- volume-io:
- volume-io.[volume]:
- some-customized-metric:
  collector: shell
  command: path/to/my/script
```

*The shell script could be REXX script to read SDSF output.*

**Interface**

- `/version`: shows metric service version and Zowe version parsed from manifest.json
- `/metrics`: list all available metric name list
- `/metrics-result`: shows key/value pair of each metric we are tracking, follow standard https://openmetrics.io/

Websocket can push metrics to registered clients.

**Key Classes**

- BaseMetricsCollector
  - RMFMetricsCollector
  - CIMMetricsCollector
  - ScriptMetricsCollector

**Possible Starter Projects:**

- https://github.com/microsoft/TypeScript-Node-Starter
- https://github.com/sahat/hackathon-starter
- https://github.com/zowe/sample-node-api
